//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportMarketGogolev.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int id { get; set; }
        public System.DateTime DateOrder { get; set; }
        public int Userid { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}
